<?php
/**
 * Copyright © 2016 FAQNext Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/**
 * @var $block \FAQ\Question\Block\Question
 */
?>
<div class="FAQ-Question">
    <h2><?php echo __('This is a Frequently Asked Questions page') ?></h2>
</div>

<div id="questions">
    <?php $items = $block->getItems(); ?>
    <?php if ($items->getSize()) : ?>
        <?php foreach ($items as $item) : ?>
            <div data-role="collapsible">
                <div data-role="trigger">
                    <h4><?php echo $item->getTheme()?></h4>
                </div>
            </div>
            <div data-role="content">
                <p class="name">
                    <span><?php echo __('Username:'); ?></span>&nbsp;
                    <span><?php echo $item->getName()?></span>
                </p>
                <p class="email">
                    <span><?php echo __('Email:'); ?></span>&nbsp;
                    <span><?php echo $item->getEmail()?></span>
                </p>
                <p class="created">
                    <span><?php echo __('Created:'); ?></span>&nbsp;
                    <span><?php echo $item->getCreationTime()?></span>
                </p>
                <p class="question">
                    <span><?php echo __('Question:'); ?></span>&nbsp;
                    <span><?php echo $item->getQuestion()?></span>
                </p>
                <p class="answer">
                    <span><?php echo __('Answer:'); ?></span>&nbsp;
                    <span><?php echo $item->getAnswer()?></span>
                </p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>








<form class="form contact"
      action="<?php echo $block->escapeUrl($block->getFormAction()); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo $block->escapeHtml(__('Ask Us')) ?></span></legend><br />
        <div class="field note no-label"><?php echo $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?></div>
        <div class="field name required">
            <label class="label" for="name"><span><?php echo $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php echo $block->escapeHtmlAttr(__('Name')) ?>" value="<?php echo $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php echo $block->escapeHtmlAttr(__('Email')) ?>" value="<?php echo $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field theme">
            <label class="label" for="theme"><span><?php echo $block->escapeHtml(__('Issue Theme')) ?></span></label>
            <div class="control">
                <input name="theme" id="theme" title="<?php echo $block->escapeHtmlAttr(__('Issue Theme')) ?>" value="<?php echo $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?php echo $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php echo $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?php echo $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<script>
    require([
        'jquery',
        'tabs'], function ($) {
        $("#questions").accordion();
    });
</script>